### ISSUE TITLE
Exception java.lang.RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by pete-adapptor** [bluecats/bluecats-android-sdk#14] opened 2017-04-20 02:19 UTC
Hi,

We have users who are experiencing the following crash:

```
Exception java.lang.RuntimeException: Package manager has died
android.app.ApplicationPackageManager.checkPermission (ApplicationPackageManager.java:353)
com.bluecats.sdk.BCLocationManager.b ()
com.bluecats.sdk.ai.d ()
com.bluecats.sdk.bd$1.run ()
java.lang.Thread.run (Thread.java:841)

Caused by android.os.DeadObjectException:
android.os.BinderProxy.transact (Binder.java)
android.content.pm.IPackageManager$Stub$Proxy.checkPermission (IPackageManager.java:2178)
android.app.ApplicationPackageManager.checkPermission (ApplicationPackageManager.java:351)
com.bluecats.sdk.BCLocationManager.b ()
com.bluecats.sdk.ai.d ()
com.bluecats.sdk.bd$1.run ()
java.lang.Thread.run (Thread.java:841)
```

API Level 19
Device: GT-I9506

Bluecats SDK version: 2.0.1

**Comment by henrybluecats** [comment] 2017-05-03 02:28
Hi,
Thanks for your reporting.
Could you please send the entire logs to developer@bluecats.com.

Regards,
Henry

**Comment by pete-adapptor** [comment] 2017-05-03 02:41
Unfortunately we don't have any logs to provide as this is all the information we have from our crash report.

The only other info we can provide is the following devices which have also experienced this crash since the initial report:
- SM-G920I - API 21 and API 23
- SM-G900I - API 23
- SM-N915G - API 23
- SM-N910G API23
- F3115 - API 23

**Comment by henrybluecats** [comment] 2017-05-03 03:05
Thanks Pete, please send what you have to us support@bluecats.com.

**Comment by henrybluecats** [comment] 2017-05-03 03:08
Thanks @pete-adapptor, did you receive any crashing on TransactionTooLargeException in your app(not in bluecats sdk)?

**Comment by pete-adapptor** [comment] 2017-05-03 03:14
No, there is no instance of that exception occurring on our crash reports.

**Comment by tranminhlan** [comment] 2017-08-14 08:45
@henrybluecats .
I have implement below code.
 mAppManagedRegion = new BCBeaconRegion("24212d3c-7cc5-4844-bcf6-5ecba50b5aa9", "REGION_IDENTIFIER");
     mBeaconManager.startMonitoringBeaconRegion(mAppManagedRegion);

And app crash please, help check it

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.bluecats.sdk.BCBeaconRegionManager.b(com.bluecats.sdk.BCBeaconRegion, boolean)' on a null object reference at com.bluecats.sdk.BCBeaconManager.startMonitoringBeaconRegion(SourceFile:101)

Please, help me check it. What's reason for crash.

**Comment by henrybluecats** [comment] 2018-04-12 01:08
Hi, sorry for late response. The SDK v2.0.7(or older) doesn't support mBeaconManager.startMonitoringBeaconRegion properly. But new SDK will be released soon.

**Closed by henrybluecats** 2018-04-12 01:08 UTC
